services:
  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "80:80"
    volumes:
      # Mount your template file into Nginx's automated template folder
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
    env_file: 
      - .env  
    environment:
      - NGINX_ENVSUBST_FILTER=^PRIVATE_IP_

    restart: always