services:
  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "80:80"
    volumes:
      # Mount your template file into Nginx's automated template folder
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
    env_file: 
      - .env  
    environment:
      # The double $$ tells Docker Compose to safely pass the literal $ to the Nginx script
      - NGINX_ENVSUBST_FILTER=$${PRIVATE_IP_AUTH} $${PRIVATE_IP_ORDER} $${PRIVATE_IP_PAYMENT} $${PRIVATE_IP_INVENTORY}

    restart: always